#!/usr/bin/env bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='adw-gtk3'
ICONS='Nordic-Folders'
FONT='Noto Sans 9'
CURSOR='BreezeX-Black'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
